export default {
    products:[{
        id: '1',
        name: 'Conjunto Turquesa',
        category: 'conjunto',
        image: '/images/Produto1.jpg',
        price: 15,
        rating: 2.5,
        numReviews: 58,
        description: 'Lorem ipsum dolor sit amet.',
    },
    {
        id: '2',
        name: 'Anel Esmeralda',
        category: 'anel',
        image: '/images/Produto2.jpg',
        price: 25,
        rating: 3.5,
        numReviews: 72,
        description: 'Lorem ipsum dolor sit amet.',
    },
    {
        id: '3',
        name: 'Anel Rubi',
        category: 'anel',
        image: '/images/Produto3.jpg',
        price: 30,
        rating: 4.5,
        numReviews: 19,
        description: 'Lorem ipsum dolor sit amet.',
    },
    {
        id: '4',
        name: 'Colar Cristal',
        category: 'colar',
        image: '/images/Produto4.jpg',
        price: 22,
        rating: 5.0,
        numReviews: 120,
        description: 'Lorem ipsum dolor sit amet.',
    },
]
}